//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentSigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentSigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap certificate_invalid {
            get {
                object obj = ResourceManager.GetObject("certificate_invalid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap certificate_valid {
            get {
                object obj = ResourceManager.GetObject("certificate_valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, certificate is not valid.
        /// </summary>
        internal static string CertificateStatusInvalid {
            get {
                return ResourceManager.GetString("CertificateStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading certificate information.
        /// </summary>
        internal static string CertificateStatusLoading {
            get {
                return ResourceManager.GetString("CertificateStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load certificate.
        /// </summary>
        internal static string CertificateStatusNotFound {
            get {
                return ResourceManager.GetString("CertificateStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is valid.
        /// </summary>
        internal static string CertificateStatusValid {
            get {
                return ResourceManager.GetString("CertificateStatusValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow always.
        /// </summary>
        internal static string DomainSettingsAllowAlways {
            get {
                return ResourceManager.GetString("DomainSettingsAllowAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow once.
        /// </summary>
        internal static string DomainSettingsAllowOnce {
            get {
                return ResourceManager.GetString("DomainSettingsAllowOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny always.
        /// </summary>
        internal static string DomainSettingsDenyAlways {
            get {
                return ResourceManager.GetString("DomainSettingsDenyAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny once.
        /// </summary>
        internal static string DomainSettingsDenyOnce {
            get {
                return ResourceManager.GetString("DomainSettingsDenyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client: {0} || Server: {1}.
        /// </summary>
        internal static string ManagerDomainsDescription {
            get {
                return ResourceManager.GetString("ManagerDomainsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needs to be restarted to load the changes.
        /// </summary>
        internal static string MessageRestartContent {
            get {
                return ResourceManager.GetString("MessageRestartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MessageRestartTitle {
            get {
                return ResourceManager.GetString("MessageRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is sending a request to {1} to sign a document.
        /// </summary>
        internal static string SigningRequestMessage {
            get {
                return ResourceManager.GetString("SigningRequestMessage", resourceCulture);
            }
        }
    }
}
